### ISSUE TITLE
Add posibility to embed into website

### ISSUE THREAD

**Issue by krislarsen** [Vatsim-Scandinavia/stands#9]
Would be lovely to see if there is a possibility to add stand availability on the airport briefing page. Either by adding the map embedded on website or create a list of all stands showing availability of all stands at the aerodrome 

I'll add VATSIM UK as an reference. They've added a map on top of the page as well a stand availability list at bottom
https://www.vatsim.uk/airports/EGLL

**Comment by blt950** [comment]
@krislarsen It's actually possible, I tested this here: https://wiki.vatsim-scandinavia.org/books/norwegian-airports-charts/page/engm-oslo-lufthavn
![image](https://github.com/Vatsim-Scandinavia/stands/assets/2505044/f29c0014-62af-44bd-9fc9-dcbe90fbe2d3)

I just need to add an update that removes all the menus and stuff, so it looks a bit more integrated

**Comment by blt950** [comment]
Tweaked and added possibility for this with use of `frameless=true` variable in URL
